apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
  labels:
    service: nginx-deployment
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
  type: NodePort
